name = "moonboard-relay"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[durable_objects.bindings]]
name = "RELAY"
class_name = "Relay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Relay"]
